all: anodecli

anodecli:
	$(TIME) python updated_anodecli.py -m arson -v ./videos/arson001-x264_JT5fU5T6.mp4 -o ./out/arson001-x264_JT5fU5T6.out.pickle

oldanodecli:
	$(TIME) python anodecli.py -m arson -v ./videos/arson001-x264_JT5fU5T6.mp4 -o ./out/arson001-x264_JT5fU5T6.out.pickle

anodeyt:
	$(TIME) python anodeyt.py -m explosion -yt https://www.youtube.com/watch?v=rZXz0sodnvo -o ./out/rZXz0sodnvo.out.pickle
